server:
  port: 8081
spring:
  application:
    name: myh-product
  cloud:
    nacos:
      discovery: # 必须要有这个层级
        server-addr: localhost:8848
        namespace: public # 可选，明确指定命名空间
        group: DEFAULT_GROUP # 可选，明确指定分组
    sentinel:
      transport:
        dashboard: localhost:8090  # sentinel控制台地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java112_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qiu@12345678
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 修正方言
    show-sql: true
