server:
  port: 8095

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


# 暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 