server:
  port: 8071
spring:
  application:
    name: myh-auth  #这个名字后面注册中心要用
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///java112_cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #  jpa配置
  jpa:
    hibernate:
      #      一旦实体类发生变化，则会自动更新这个数据库的表内容
      # DDL数据定义语言（建表建库） DCL(用户)  DQL（CRUD）  DML（数据权限操作）
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 修正方言
    show-sql: true #打印sql语句执行慢的东西